name: Fastify Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Install Fastify Dependencies
        run: ./batect install-dep

      - name: Run testcase
        run: ./batect test-ci

      - name: Perform Linting
        run: ./batect lint

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Login heroku container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build docker image and push to heroku registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a fastify-app1 web

      - name: Run docker image on heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a fastify-app1 web
